
development:
  adapter: postgresql
  encoding: unicode
  database: finish1_development
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: finish1_test
  pool: 5
  host: localhost
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: finish1_production
  pool: 5
  username:
  password:
